### ISSUE TITLE
Not able to complete an "rping" from inside a container

### ISSUE THREAD

**Issue by dacrespi** [Mellanox/docker-passthrough-plugin#11]
Running the sriov-plugin from: https://hub.docker.com/r/rdma/sriov-plugin
and testing out if rping works, which it fails when trying to resolve the address.

sudo rping -s -v  -p 1922 -d
created cm_id 0x55db7906e360
rdma_bind_addr successful
rdma_listen

$ sudo rping -c -v -a 192.168.3.100 -p 1922 -C 10 -d
created cm_id 0x559e199b8f70
cma_event type RDMA_CM_EVENT_ADDR_ERROR cma_id 0x559e199b8f70 (parent)
cma event RDMA_CM_EVENT_ADDR_ERROR, error -19
waiting for addr/route resolution state 1
destroy cm_id 0x559e199b8f70

The sriov container is built using:
docker run -d --name sriov -v /run/docker/plugins:/run/docker/plugins -v /etc/docker:/etc/docker -v /var/run:/var/run --net=host --privileged rdma/sriov-plugin

And the network is created:
docker network create -d sriov --subnet=192.168.3.0/24 --gateway=192.168.3.1 -o netdevice=enp59s0f1 net

ibv_rc_pingpong test completes correctly.

**Comment by paravmellanox** [comment]
@dacrespi which MOFED version is used in host kernel?

**Comment by dacrespi** [comment]
Hello Parav, thanks for reaching out.
I’m running Ubuntu 18.04, which has the 4.15 Kernel.  I looked at your presentation
yesterday (roce-containers.pdf) and see that we need to be at least with the 4.19 kernel to make this
work… is that correct?  I was planning on doing that this morning.

Regards,

           David

________________________________

**Comment by dacrespi** [comment]
Parav,
Updating to the latest kernel does allow the rping to work.
Sorry for the trouble… I didn’t see your presentation until after I filed the bug.

Regards,

           David


________________________________

**Comment by dacrespi** [comment]
After updating to the 5.0.21 kernel, rping worked fine!

**Comment by paravmellanox** [comment]
@dacrespi, great.
Happy to see it working.
